/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SwarmAgentRegistryLink {
  export type AgentStruct = {
    agentAddress: AddressLike;
    name: string;
    skills: string;
    asn: string;
    feeRate: BigNumberish;
    creditScore: BigNumberish;
    trustScore: BigNumberish;
    active: boolean;
    registeredAt: BigNumberish;
  };

  export type AgentStructOutput = [
    agentAddress: string,
    name: string,
    skills: string,
    asn: string,
    feeRate: bigint,
    creditScore: bigint,
    trustScore: bigint,
    active: boolean,
    registeredAt: bigint
  ] & {
    agentAddress: string;
    name: string;
    skills: string;
    asn: string;
    feeRate: bigint;
    creditScore: bigint;
    trustScore: bigint;
    active: boolean;
    registeredAt: bigint;
  };
}

export interface SwarmAgentRegistryLinkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentCount"
      | "agentList"
      | "agents"
      | "asnToAgent"
      | "deactivateAgent"
      | "getAgent"
      | "getAgentByASN"
      | "getAllAgents"
      | "isRegistered"
      | "owner"
      | "registerAgent"
      | "registerAgentFor"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateCredit"
      | "updateSkills"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentRegistered"
      | "CreditUpdated"
      | "OwnershipTransferred"
      | "SkillsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "asnToAgent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentByASN",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgentFor",
    values: [AddressLike, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCredit",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSkills",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asnToAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByASN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgentFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSkills",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agentAddress: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [agentAddress: string, timestamp: bigint];
  export interface OutputObject {
    agentAddress: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentAddress: AddressLike,
    name: string,
    asn: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentAddress: string,
    name: string,
    asn: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentAddress: string;
    name: string;
    asn: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditUpdatedEvent {
  export type InputTuple = [
    agentAddress: AddressLike,
    creditScore: BigNumberish,
    trustScore: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentAddress: string,
    creditScore: bigint,
    trustScore: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentAddress: string;
    creditScore: bigint;
    trustScore: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkillsUpdatedEvent {
  export type InputTuple = [
    agentAddress: AddressLike,
    newSkills: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentAddress: string,
    newSkills: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentAddress: string;
    newSkills: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwarmAgentRegistryLink extends BaseContract {
  connect(runner?: ContractRunner | null): SwarmAgentRegistryLink;
  waitForDeployment(): Promise<this>;

  interface: SwarmAgentRegistryLinkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        agentAddress: string;
        name: string;
        skills: string;
        asn: string;
        feeRate: bigint;
        creditScore: bigint;
        trustScore: bigint;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  asnToAgent: TypedContractMethod<[arg0: string], [string], "view">;

  deactivateAgent: TypedContractMethod<[], [void], "nonpayable">;

  getAgent: TypedContractMethod<
    [agentAddr: AddressLike],
    [SwarmAgentRegistryLink.AgentStructOutput],
    "view"
  >;

  getAgentByASN: TypedContractMethod<
    [asn: string],
    [SwarmAgentRegistryLink.AgentStructOutput],
    "view"
  >;

  getAllAgents: TypedContractMethod<
    [],
    [SwarmAgentRegistryLink.AgentStructOutput[]],
    "view"
  >;

  isRegistered: TypedContractMethod<
    [agentAddr: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [name: string, skills: string, asn: string, feeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAgentFor: TypedContractMethod<
    [
      agentAddr: AddressLike,
      name: string,
      skills: string,
      asn: string,
      feeRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCredit: TypedContractMethod<
    [
      agentAddr: AddressLike,
      creditScore: BigNumberish,
      trustScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateSkills: TypedContractMethod<[newSkills: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        agentAddress: string;
        name: string;
        skills: string;
        asn: string;
        feeRate: bigint;
        creditScore: bigint;
        trustScore: bigint;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "asnToAgent"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentAddr: AddressLike],
    [SwarmAgentRegistryLink.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentByASN"
  ): TypedContractMethod<
    [asn: string],
    [SwarmAgentRegistryLink.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<
    [],
    [SwarmAgentRegistryLink.AgentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[agentAddr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [name: string, skills: string, asn: string, feeRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgentFor"
  ): TypedContractMethod<
    [
      agentAddr: AddressLike,
      name: string,
      skills: string,
      asn: string,
      feeRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCredit"
  ): TypedContractMethod<
    [
      agentAddr: AddressLike,
      creditScore: BigNumberish,
      trustScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSkills"
  ): TypedContractMethod<[newSkills: string], [void], "nonpayable">;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CreditUpdated"
  ): TypedContractEvent<
    CreditUpdatedEvent.InputTuple,
    CreditUpdatedEvent.OutputTuple,
    CreditUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SkillsUpdated"
  ): TypedContractEvent<
    SkillsUpdatedEvent.InputTuple,
    SkillsUpdatedEvent.OutputTuple,
    SkillsUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(address,uint256)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(address,string,string,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "CreditUpdated(address,uint16,uint8,uint256)": TypedContractEvent<
      CreditUpdatedEvent.InputTuple,
      CreditUpdatedEvent.OutputTuple,
      CreditUpdatedEvent.OutputObject
    >;
    CreditUpdated: TypedContractEvent<
      CreditUpdatedEvent.InputTuple,
      CreditUpdatedEvent.OutputTuple,
      CreditUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SkillsUpdated(address,string,uint256)": TypedContractEvent<
      SkillsUpdatedEvent.InputTuple,
      SkillsUpdatedEvent.OutputTuple,
      SkillsUpdatedEvent.OutputObject
    >;
    SkillsUpdated: TypedContractEvent<
      SkillsUpdatedEvent.InputTuple,
      SkillsUpdatedEvent.OutputTuple,
      SkillsUpdatedEvent.OutputObject
    >;
  };
}
