/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SwarmTaskBoardLink {
  export type TaskStruct = {
    taskId: BigNumberish;
    vault: AddressLike;
    title: string;
    description: string;
    requiredSkills: string;
    deadline: BigNumberish;
    budget: BigNumberish;
    poster: AddressLike;
    claimedBy: AddressLike;
    deliveryHash: BytesLike;
    createdAt: BigNumberish;
    status: BigNumberish;
  };

  export type TaskStructOutput = [
    taskId: bigint,
    vault: string,
    title: string,
    description: string,
    requiredSkills: string,
    deadline: bigint,
    budget: bigint,
    poster: string,
    claimedBy: string,
    deliveryHash: string,
    createdAt: bigint,
    status: bigint
  ] & {
    taskId: bigint;
    vault: string;
    title: string;
    description: string;
    requiredSkills: string;
    deadline: bigint;
    budget: bigint;
    poster: string;
    claimedBy: string;
    deliveryHash: string;
    createdAt: bigint;
    status: bigint;
  };
}

export interface SwarmTaskBoardLinkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveDelivery"
      | "claimTask"
      | "disputeDelivery"
      | "getAllTasks"
      | "getOpenTasks"
      | "getTask"
      | "linkToken"
      | "owner"
      | "postTask"
      | "renounceOwnership"
      | "submitDelivery"
      | "taskCount"
      | "tasks"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliveryApproved"
      | "DeliveryDisputed"
      | "DeliverySubmitted"
      | "OwnershipTransferred"
      | "TaskClaimed"
      | "TaskPosted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTasks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenTasks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "linkToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postTask",
    values: [AddressLike, string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitDelivery",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "taskCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "linkToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DeliveryApprovedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    agent: AddressLike,
    payout: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    agent: string,
    payout: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    agent: string;
    payout: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryDisputedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    poster: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, poster: string, timestamp: bigint];
  export interface OutputObject {
    taskId: bigint;
    poster: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliverySubmittedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    agent: AddressLike,
    deliveryHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    agent: string,
    deliveryHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    agent: string;
    deliveryHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskClaimedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    agent: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, agent: string, timestamp: bigint];
  export interface OutputObject {
    taskId: bigint;
    agent: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskPostedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    poster: AddressLike,
    vault: AddressLike,
    title: string,
    budget: BigNumberish,
    deadline: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    poster: string,
    vault: string,
    title: string,
    budget: bigint,
    deadline: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    poster: string;
    vault: string;
    title: string;
    budget: bigint;
    deadline: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwarmTaskBoardLink extends BaseContract {
  connect(runner?: ContractRunner | null): SwarmTaskBoardLink;
  waitForDeployment(): Promise<this>;

  interface: SwarmTaskBoardLinkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveDelivery: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  disputeDelivery: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllTasks: TypedContractMethod<
    [],
    [SwarmTaskBoardLink.TaskStructOutput[]],
    "view"
  >;

  getOpenTasks: TypedContractMethod<
    [],
    [SwarmTaskBoardLink.TaskStructOutput[]],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [SwarmTaskBoardLink.TaskStructOutput],
    "view"
  >;

  linkToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  postTask: TypedContractMethod<
    [
      vault: AddressLike,
      title: string,
      description: string,
      requiredSkills: string,
      deadline: BigNumberish,
      budgetLink: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitDelivery: TypedContractMethod<
    [taskId: BigNumberish, deliveryHash: BytesLike],
    [void],
    "nonpayable"
  >;

  taskCount: TypedContractMethod<[], [bigint], "view">;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint
      ] & {
        taskId: bigint;
        vault: string;
        title: string;
        description: string;
        requiredSkills: string;
        deadline: bigint;
        budget: bigint;
        poster: string;
        claimedBy: string;
        deliveryHash: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveDelivery"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeDelivery"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllTasks"
  ): TypedContractMethod<[], [SwarmTaskBoardLink.TaskStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getOpenTasks"
  ): TypedContractMethod<[], [SwarmTaskBoardLink.TaskStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [SwarmTaskBoardLink.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "linkToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postTask"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      title: string,
      description: string,
      requiredSkills: string,
      deadline: BigNumberish,
      budgetLink: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitDelivery"
  ): TypedContractMethod<
    [taskId: BigNumberish, deliveryHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint
      ] & {
        taskId: bigint;
        vault: string;
        title: string;
        description: string;
        requiredSkills: string;
        deadline: bigint;
        budget: bigint;
        poster: string;
        claimedBy: string;
        deliveryHash: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DeliveryApproved"
  ): TypedContractEvent<
    DeliveryApprovedEvent.InputTuple,
    DeliveryApprovedEvent.OutputTuple,
    DeliveryApprovedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryDisputed"
  ): TypedContractEvent<
    DeliveryDisputedEvent.InputTuple,
    DeliveryDisputedEvent.OutputTuple,
    DeliveryDisputedEvent.OutputObject
  >;
  getEvent(
    key: "DeliverySubmitted"
  ): TypedContractEvent<
    DeliverySubmittedEvent.InputTuple,
    DeliverySubmittedEvent.OutputTuple,
    DeliverySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskClaimed"
  ): TypedContractEvent<
    TaskClaimedEvent.InputTuple,
    TaskClaimedEvent.OutputTuple,
    TaskClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskPosted"
  ): TypedContractEvent<
    TaskPostedEvent.InputTuple,
    TaskPostedEvent.OutputTuple,
    TaskPostedEvent.OutputObject
  >;

  filters: {
    "DeliveryApproved(uint256,address,uint256,uint256)": TypedContractEvent<
      DeliveryApprovedEvent.InputTuple,
      DeliveryApprovedEvent.OutputTuple,
      DeliveryApprovedEvent.OutputObject
    >;
    DeliveryApproved: TypedContractEvent<
      DeliveryApprovedEvent.InputTuple,
      DeliveryApprovedEvent.OutputTuple,
      DeliveryApprovedEvent.OutputObject
    >;

    "DeliveryDisputed(uint256,address,uint256)": TypedContractEvent<
      DeliveryDisputedEvent.InputTuple,
      DeliveryDisputedEvent.OutputTuple,
      DeliveryDisputedEvent.OutputObject
    >;
    DeliveryDisputed: TypedContractEvent<
      DeliveryDisputedEvent.InputTuple,
      DeliveryDisputedEvent.OutputTuple,
      DeliveryDisputedEvent.OutputObject
    >;

    "DeliverySubmitted(uint256,address,bytes32,uint256)": TypedContractEvent<
      DeliverySubmittedEvent.InputTuple,
      DeliverySubmittedEvent.OutputTuple,
      DeliverySubmittedEvent.OutputObject
    >;
    DeliverySubmitted: TypedContractEvent<
      DeliverySubmittedEvent.InputTuple,
      DeliverySubmittedEvent.OutputTuple,
      DeliverySubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskClaimed(uint256,address,uint256)": TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;
    TaskClaimed: TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;

    "TaskPosted(uint256,address,address,string,uint256,uint256,uint256)": TypedContractEvent<
      TaskPostedEvent.InputTuple,
      TaskPostedEvent.OutputTuple,
      TaskPostedEvent.OutputObject
    >;
    TaskPosted: TypedContractEvent<
      TaskPostedEvent.InputTuple,
      TaskPostedEvent.OutputTuple,
      TaskPostedEvent.OutputObject
    >;
  };
}
