/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SwarmASNRegistry {
  export type ASNRecordStruct = {
    asn: string;
    owner: AddressLike;
    agentName: string;
    agentType: string;
    creditScore: BigNumberish;
    trustScore: BigNumberish;
    tasksCompleted: BigNumberish;
    totalVolumeWei: BigNumberish;
    registeredAt: BigNumberish;
    lastActive: BigNumberish;
    active: boolean;
  };

  export type ASNRecordStructOutput = [
    asn: string,
    owner: string,
    agentName: string,
    agentType: string,
    creditScore: bigint,
    trustScore: bigint,
    tasksCompleted: bigint,
    totalVolumeWei: bigint,
    registeredAt: bigint,
    lastActive: bigint,
    active: boolean
  ] & {
    asn: string;
    owner: string;
    agentName: string;
    agentType: string;
    creditScore: bigint;
    trustScore: bigint;
    tasksCompleted: bigint;
    totalVolumeWei: bigint;
    registeredAt: bigint;
    lastActive: bigint;
    active: boolean;
  };
}

export interface SwarmASNRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allASNs"
      | "getAllRecords"
      | "getRecord"
      | "getRecordByOwner"
      | "owner"
      | "ownerToASN"
      | "recordTaskCompletion"
      | "records"
      | "registerASN"
      | "registerASNFor"
      | "renounceOwnership"
      | "totalRecords"
      | "transferOwnership"
      | "updateCredit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ASNRegistered"
      | "CreditUpdated"
      | "OwnershipTransferred"
      | "TaskCompleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allASNs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRecords",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getRecord", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRecordByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerToASN",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTaskCompletion",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "records", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerASN",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerASNFor",
    values: [AddressLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCredit",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allASNs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerToASN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordTaskCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerASN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerASNFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCredit",
    data: BytesLike
  ): Result;
}

export namespace ASNRegisteredEvent {
  export type InputTuple = [
    asn: string,
    owner: AddressLike,
    agentName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    asn: string,
    owner: string,
    agentName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    asn: string;
    owner: string;
    agentName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditUpdatedEvent {
  export type InputTuple = [
    asn: string,
    creditScore: BigNumberish,
    trustScore: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    asn: string,
    creditScore: bigint,
    trustScore: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    asn: string;
    creditScore: bigint;
    trustScore: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [
    asn: string,
    newTotal: BigNumberish,
    volume: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    asn: string,
    newTotal: bigint,
    volume: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    asn: string;
    newTotal: bigint;
    volume: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwarmASNRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SwarmASNRegistry;
  waitForDeployment(): Promise<this>;

  interface: SwarmASNRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allASNs: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getAllRecords: TypedContractMethod<
    [],
    [SwarmASNRegistry.ASNRecordStructOutput[]],
    "view"
  >;

  getRecord: TypedContractMethod<
    [asn: string],
    [SwarmASNRegistry.ASNRecordStructOutput],
    "view"
  >;

  getRecordByOwner: TypedContractMethod<
    [owner: AddressLike],
    [SwarmASNRegistry.ASNRecordStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ownerToASN: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  recordTaskCompletion: TypedContractMethod<
    [asn: string, volumeWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  records: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        asn: string;
        owner: string;
        agentName: string;
        agentType: string;
        creditScore: bigint;
        trustScore: bigint;
        tasksCompleted: bigint;
        totalVolumeWei: bigint;
        registeredAt: bigint;
        lastActive: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  registerASN: TypedContractMethod<
    [asn: string, agentName: string, agentType: string],
    [void],
    "nonpayable"
  >;

  registerASNFor: TypedContractMethod<
    [owner: AddressLike, asn: string, agentName: string, agentType: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalRecords: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCredit: TypedContractMethod<
    [asn: string, creditScore: BigNumberish, trustScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allASNs"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAllRecords"
  ): TypedContractMethod<
    [],
    [SwarmASNRegistry.ASNRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [asn: string],
    [SwarmASNRegistry.ASNRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordByOwner"
  ): TypedContractMethod<
    [owner: AddressLike],
    [SwarmASNRegistry.ASNRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerToASN"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "recordTaskCompletion"
  ): TypedContractMethod<
    [asn: string, volumeWei: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        asn: string;
        owner: string;
        agentName: string;
        agentType: string;
        creditScore: bigint;
        trustScore: bigint;
        tasksCompleted: bigint;
        totalVolumeWei: bigint;
        registeredAt: bigint;
        lastActive: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerASN"
  ): TypedContractMethod<
    [asn: string, agentName: string, agentType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerASNFor"
  ): TypedContractMethod<
    [owner: AddressLike, asn: string, agentName: string, agentType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCredit"
  ): TypedContractMethod<
    [asn: string, creditScore: BigNumberish, trustScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ASNRegistered"
  ): TypedContractEvent<
    ASNRegisteredEvent.InputTuple,
    ASNRegisteredEvent.OutputTuple,
    ASNRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CreditUpdated"
  ): TypedContractEvent<
    CreditUpdatedEvent.InputTuple,
    CreditUpdatedEvent.OutputTuple,
    CreditUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;

  filters: {
    "ASNRegistered(string,address,string,uint256)": TypedContractEvent<
      ASNRegisteredEvent.InputTuple,
      ASNRegisteredEvent.OutputTuple,
      ASNRegisteredEvent.OutputObject
    >;
    ASNRegistered: TypedContractEvent<
      ASNRegisteredEvent.InputTuple,
      ASNRegisteredEvent.OutputTuple,
      ASNRegisteredEvent.OutputObject
    >;

    "CreditUpdated(string,uint16,uint8,uint256)": TypedContractEvent<
      CreditUpdatedEvent.InputTuple,
      CreditUpdatedEvent.OutputTuple,
      CreditUpdatedEvent.OutputObject
    >;
    CreditUpdated: TypedContractEvent<
      CreditUpdatedEvent.InputTuple,
      CreditUpdatedEvent.OutputTuple,
      CreditUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskCompleted(string,uint256,uint256,uint256)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
  };
}
