/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SwarmTreasuryLinkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPUTE_BPS"
      | "GROWTH_BPS"
      | "RESERVE_BPS"
      | "agentAddress"
      | "computeBalance"
      | "depositRevenue"
      | "getPnL"
      | "growthBalance"
      | "linkToken"
      | "owner"
      | "renounceOwnership"
      | "reserveBalance"
      | "setAgentAddress"
      | "totalRevenue"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAddressUpdated"
      | "OwnershipTransferred"
      | "RevenueDeposited"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPUTE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GROWTH_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPnL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "growthBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "linkToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPUTE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GROWTH_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPnL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "growthBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "linkToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AgentAddressUpdatedEvent {
  export type InputTuple = [newAgent: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [newAgent: string, timestamp: bigint];
  export interface OutputObject {
    newAgent: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueDepositedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [to: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwarmTreasuryLink extends BaseContract {
  connect(runner?: ContractRunner | null): SwarmTreasuryLink;
  waitForDeployment(): Promise<this>;

  interface: SwarmTreasuryLinkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPUTE_BPS: TypedContractMethod<[], [bigint], "view">;

  GROWTH_BPS: TypedContractMethod<[], [bigint], "view">;

  RESERVE_BPS: TypedContractMethod<[], [bigint], "view">;

  agentAddress: TypedContractMethod<[], [string], "view">;

  computeBalance: TypedContractMethod<[], [bigint], "view">;

  depositRevenue: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPnL: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalRevenue: bigint;
        _computeBalance: bigint;
        _growthBalance: bigint;
        _reserveBalance: bigint;
      }
    ],
    "view"
  >;

  growthBalance: TypedContractMethod<[], [bigint], "view">;

  linkToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveBalance: TypedContractMethod<[], [bigint], "view">;

  setAgentAddress: TypedContractMethod<
    [_agentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  totalRevenue: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPUTE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GROWTH_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESERVE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "computeBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositRevenue"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPnL"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalRevenue: bigint;
        _computeBalance: bigint;
        _growthBalance: bigint;
        _reserveBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "growthBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "linkToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAgentAddress"
  ): TypedContractMethod<[_agentAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentAddressUpdated"
  ): TypedContractEvent<
    AgentAddressUpdatedEvent.InputTuple,
    AgentAddressUpdatedEvent.OutputTuple,
    AgentAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RevenueDeposited"
  ): TypedContractEvent<
    RevenueDepositedEvent.InputTuple,
    RevenueDepositedEvent.OutputTuple,
    RevenueDepositedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentAddressUpdated(address,uint256)": TypedContractEvent<
      AgentAddressUpdatedEvent.InputTuple,
      AgentAddressUpdatedEvent.OutputTuple,
      AgentAddressUpdatedEvent.OutputObject
    >;
    AgentAddressUpdated: TypedContractEvent<
      AgentAddressUpdatedEvent.InputTuple,
      AgentAddressUpdatedEvent.OutputTuple,
      AgentAddressUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RevenueDeposited(address,uint256,uint256)": TypedContractEvent<
      RevenueDepositedEvent.InputTuple,
      RevenueDepositedEvent.OutputTuple,
      RevenueDepositedEvent.OutputObject
    >;
    RevenueDeposited: TypedContractEvent<
      RevenueDepositedEvent.InputTuple,
      RevenueDepositedEvent.OutputTuple,
      RevenueDepositedEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
